config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :dreams, only: [:new, :create, :show, :destroy, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dream.rb
class Dream < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController

  def create
    @dream = Dream.new(dream_params)
    if @dream.save
      redirect_to dream_path(@dream)
    else
      render :new
    end
  end

  def show
    @dream = Dream.find(params[:id])
  end

  def new
    @dream = Dream.new
  end

  def index
    @dreams = Dream.all
  end

  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy
    redirect_to dreams_path
  end
  def edit
    @dream = Dream.find(params[:id])
  end

  private
# ici je définie ce que je vais permettre qu'on envoie dans la variable dream_params
  def dream_params
     params.require(:dream).permit( :description, :date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
# saute=skip saute le before action seulement pour page home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dreams/index.html.erb
<div class="row" >
  <div class="col-xs-6 col-xs-offset-3" >

    <h1>Rêves</h1>
      <% @dreams.each do |dream| %>
    <ul>
      <li>Le <%= dream.date %></li>
      <li><%= dream.description %></li>

       <%= link_to 'supprimer', dream_path(dream), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm btntous" %>
       <%= link_to "Mon rêve",new_dream_path , class: "btn btn-primary btn-sm  .disabled" %>

          </ul>
    <% end %>
    <%= link_to "Retour",root_path , class: "btn btn-outline-primary btn-sm" %>
  </div>
</div>

app/views/dreams/new.html.erb
<div class="container">
  <div class="row">
      <div class="col-xs-6 col-xs-offset-3 reve">
        <h1>Mon rêve d'aujourd'hui</h1>
          <%= simple_form_for @dream do |f| %>
            <%= f.error_notification %>
            <%= f.input :description %>
            <%= f.input :date %>
          <%= f.button :submit, class: "btn btn-primary btn-sm" %>
          <% end %>

        <div/>
      <div/>
    <div/>

app/views/dreams/show.html.erb
<div class="row" >
  <div class="col-xs-6 col-xs-offset-3" >
    <h1>Rêve</h1>
      <ul>
        <li> <%= @dream.description %> </li>
        <li> Le: <%= @dream.date %> </li>
      </ul>
      <%= link_to 'Tous mes rêves', dreams_path,  class: "btn btn-primary btn-lg btntous" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DREAMCATCHER</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->

  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://optimistick.fr/628-thickbox_default/attrape-reves.jpg');">
  <div class="banner-content">
    <h1>Dream Catcher</h1>
    <p>L'appli qui retient tes rêves'</p>


    <%= link_to "Start now",new_dream_path , class: "btn btn-primary btn-lg  .disabled" %>


  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://img1.lafourmicreative.fr/194246-large_default2/pochoir-a4-efco-attrape-reves.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Time to wake-up", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://www.snut.fr/wp-content/uploads/2015/08/dessin-de-visage-3-784x1024.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>